### ISSUE TITLE
Is it possible to use `DeviceConnect` policy instead of `iothubowner`? 

### ISSUE THREAD

**Issue by openedhardware** [jonbgallant/azure-iot-rest#2]
I just changed the policyKeyName from `iothubowner` to `device` and used a key with `DeviceConnect` policy. 
https://github.com/jonbgallant/azure-iot-rest/blob/master/data-plane/devices/files/file-upload.py#L28

But I am getting 401 error like this:

```
https://devlng.azure-devices.net/devices/00-14-22-01-23-45/files?api-version=2016-02-03
401
{"Message":"ErrorCode:IotHubUnauthorizedAccess;Unauthorized","ExceptionMessage":"Tracking ID:af9080a9df7146e1b0afe3c179add4b3-G:4-TimeStamp:12/01/2017 22:46:50"}
```

Any idea?

**Comment by jonbgallant** [comment]
It works for me:

1. Make sure you are using the 'device' primary key, not the 'iothubowner' key
1. I updated the script to now allow you to specify a `--key-name` parameter.

Please have a look, try again and let me know if you continue to have issues with this
https://github.com/jonbgallant/azure-iot-rest/blob/master/data-plane/devices/files/file-upload.py

Thanks,
Jon

**Comment by openedhardware** [comment]
Yeah, it works after fixing an issue on the key.
Thanks a lot!

**Comment by jonbgallant** [comment]
Excellent.  Thanks for the comments...helped me beef up the script a little :)
